Get rid of the .src. files and use res-copy script instead; use Xcode 2.2 for universal build
git-svn-id: https://svn.r-project.org/R-packages/trunk/Mac-GUI@2270 694ef91d-65df-0310-b7bb-92e67a308ead

diff --git a/updateSVN b/updateSVN
--- a/updateSVN
+++ b/updateSVN
@@ -1,23 +1,32 @@
 #!/bin/sh
 
-echo `pwd`
+if [ -z "$1" -o -z "$2" ]; then
+    echo ""
+    echo " Usage: updateSVN <src-root> <target-resources-dir>"
+    echo ""
+    exit 1
+fi
+
+OWD=`pwd`
+cd "$1"
 SVNREV=`sed -n 's/.*revision="\(.*\)".*/\1/p' .svn/entries`
 echo "Revision: $SVNREV"
 
 if [ -z "$SVNREV" ]; then
     echo "Cannot determine SVN revision."
-    exit 1
+    exit 2
 fi
 
-if [ ! -e English.lproj/InfoPlist.src.strings ]; then
-    echo "Cannot find English.lproj/InfoPlist.src.strings"
+if [ ! -e $1/English.lproj/InfoPlist.strings ]; then
+    echo "Cannot find $1/English.lproj/InfoPlist.strings"
     exit 2;
 fi
-if [ ! -e Info.src.plist ]; then
-    echo "Cannot find Info.src.plist"
+if [ ! -e $1/Info.plist ]; then
+    echo "Cannot find Info.plist"
     exit 3;
 fi
 
-sed "s/%SVN%/$SVNREV/g" English.lproj/InfoPlist.src.strings > English.lproj/InfoPlist.strings
-sed "s/%SVN%/$SVNREV/g" Info.src.plist > Info.plist
+sed "s/%SVN%/$SVNREV/g" $1/English.lproj/InfoPlist.strings > $2/English.lproj/InfoPlist.strings
+sed "s/%SVN%/$SVNREV/g" $1/Info.plist > $2/Info.plist
 
+exit 0
